"""
Django settings for hcndash project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local secrets (e.g. Oracle credentials) live in a gitignored .env file,
# never in this file.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t9ul0=slskm5*(g#a09h=2=5-))0)m&-eye&6umb+m3y=fae&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'archive',
    'spe_report',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hcndash.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hcndash.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # Link to the corporate Oracle server that holds the SPE source data.
    # Not managed by Django migrations - it's queried/written directly via
    # django.db.connections['oracle'] from views/management commands.
    # Credentials come from the local .env file (see .env.example); only
    # reachable from the Sonatrach internal network.
    'oracle': {
        'ENGINE': 'django.db.backends.oracle',
        # PDBPROCSPE is a pluggable-database SERVICE_NAME, not a SID, so
        # HOST/PORT can't be passed separately - Django's oracle backend
        # builds a SID-style DSN from those. Passing a full Easy Connect
        # string as NAME with HOST/PORT left blank makes Django use it
        # verbatim (see django.db.backends.oracle.utils.dsn).
        'NAME': '{host}:{port}/{service}'.format(
            host=os.environ.get('ORACLE_SPE_HOST', ''),
            port=os.environ.get('ORACLE_SPE_PORT', '1521'),
            service=os.environ.get('ORACLE_SPE_SERVICE', ''),
        ) if os.environ.get('ORACLE_SPE_HOST') else '',
        'USER': os.environ.get('ORACLE_SPE_USER', ''),
        'PASSWORD': os.environ.get('ORACLE_SPE_PASSWORD', ''),
        'HOST': '',
        'PORT': '',
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# django.contrib.messages tags its ERROR level "error" by default; map it to
# Bootstrap's "danger" so messages.error(...) renders with alert-danger.
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Authentication
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'spe_report:period_list'
LOGOUT_REDIRECT_URL = 'login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
