# Generated by Django 6.0 on 2026-09-21 10:20

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['structure', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='MasterCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='MasterEntite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['rapport', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('utilise_previsionnel', models.BooleanField(default=True, help_text='Whether this report tracks a Prévision column (some, like Export Val, only track Réalisation).')),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, unique=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('dont_libelle', models.CharField(blank=True, help_text="Label of this category's 'dont ...' breakdown row, if it has one (e.g. 'dont Cadres Sup.').", max_length=250)),
                ('master_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='spe_report.mastercategorie')),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='LigneMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('master_entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_mesure', to='spe_report.masterentite')),
            ],
            options={
                'ordering': ['master_entite', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['annee', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('numero', 'annee'), name='uniq_mois_numero_annee')],
            },
        ),
        migrations.CreateModel(
            name='PeriodeRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis')], default='brouillon', max_length=20)),
                ('soumis_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='spe_report.mois')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mois__annee', '-mois__numero'],
                'permissions': [('reopen_periode', 'Can reopen a submitted period')],
            },
        ),
        migrations.AddField(
            model_name='masterentite',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_entites', to='spe_report.rapport'),
        ),
        migrations.CreateModel(
            name='MontantInvestissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_objectif_revise', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montants_investissement', to='spe_report.action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montants_investissement', to='spe_report.mois')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montants_investissement', to='spe_report.structure')),
            ],
            options={
                'ordering': ['mois', 'structure', 'action'],
            },
        ),
        migrations.AddField(
            model_name='action',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='spe_report.structure'),
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_previsionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_realisation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_realisation_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_previsionnel_cumul', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_realisation_cumul', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_realisation_cumul_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ligne_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='spe_report.lignemesure')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='spe_report.mois')),
                ('type_participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='spe_report.typeparticipation')),
            ],
            options={
                'ordering': ['ligne_mesure', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='LigneMesureParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('ligne_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='spe_report.lignemesure')),
                ('type_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_associations', to='spe_report.typeparticipation')),
            ],
            options={
                'ordering': ['ligne_mesure', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='lignemesure',
            name='types_participation',
            field=models.ManyToManyField(blank=True, related_name='lignes_mesure', through='spe_report.LigneMesureParticipation', to='spe_report.typeparticipation'),
        ),
        migrations.AddField(
            model_name='lignemesure',
            name='unite_mesure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_mesure', to='spe_report.unitemesure'),
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification')], max_length=10)),
                ('snapshot', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='spe_report__content_1ac7f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Effectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectifs', to='spe_report.categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectifs', to='spe_report.mois')),
            ],
            options={
                'ordering': ['mois', 'categorie'],
                'constraints': [models.UniqueConstraint(fields=('categorie', 'mois'), name='uniq_effectif_categorie_mois')],
            },
        ),
        migrations.CreateModel(
            name='DontEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valeur_n1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dont_effectifs', to='spe_report.categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dont_effectifs', to='spe_report.mois')),
            ],
            options={
                'ordering': ['mois', 'categorie'],
                'constraints': [models.UniqueConstraint(fields=('categorie', 'mois'), name='uniq_dont_effectif_categorie_mois')],
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ligne_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='spe_report.lignemesure')),
            ],
            options={
                'ordering': ['annee', 'ligne_mesure'],
                'constraints': [models.UniqueConstraint(fields=('ligne_mesure', 'annee'), name='uniq_objectif_ligne_annee')],
            },
        ),
        migrations.AddConstraint(
            model_name='masterentite',
            constraint=models.UniqueConstraint(fields=('rapport', 'libelle'), name='uniq_master_entite_rapport_libelle'),
        ),
        migrations.AddConstraint(
            model_name='montantinvestissement',
            constraint=models.UniqueConstraint(fields=('mois', 'structure', 'action'), name='uniq_investissement_mois_structure_action'),
        ),
        migrations.AddConstraint(
            model_name='montantinvestissement',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', True)), fields=('mois', 'structure'), name='uniq_investissement_mois_structure_total'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('structure', 'libelle'), name='uniq_action_structure_libelle'),
        ),
        migrations.AddConstraint(
            model_name='mesure',
            constraint=models.UniqueConstraint(fields=('ligne_mesure', 'mois', 'type_participation'), name='uniq_mesure_ligne_mois_participation'),
        ),
        migrations.AddConstraint(
            model_name='mesure',
            constraint=models.UniqueConstraint(condition=models.Q(('type_participation__isnull', True)), fields=('ligne_mesure', 'mois'), name='uniq_mesure_ligne_mois_total'),
        ),
        migrations.AddConstraint(
            model_name='lignemesureparticipation',
            constraint=models.UniqueConstraint(fields=('ligne_mesure', 'type_participation'), name='uniq_ligne_mesure_type_participation'),
        ),
    ]
