# Generated by Django 6.0 on 2026-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spe_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perioderapport',
            options={'ordering': ['-mois__annee', '-mois__numero']},
        ),
    ]
